import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import utilisateursRouter from "./utilisateurs";
import etablissementsRouter from "./etablissements";
import statsRouter from "./stats";
import elevesRouter from "./eleves";
import classesRouter from "./classes";
import anneesScolairesRouter from "./anneesScolaires";
import filieresRouter from "./filieres";
import creneauxRouter from "./creneaux";
import sallesRouter from "./salles";
import emploisDuTempsRouter from "./emploisDuTemps";
import cahierTextesRouter from "./cahierTextes";
import appelsRouter from "./appels";
import notesRouter from "./notes";
import matieresConfigRouter from "./matieresConfig";
import bulletinsRouter from "./bulletins";
import conseilsClasseRouter from "./conseilsClasse";
import absencesRouter from "./absences";
import notificationsRouter from "./notifications";
import portailParentRouter from "./portailParent";
import messagesRouter from "./messages";
import rendezVousRouter from "./rendezVous";
import annoncesRouter from "./annonces";
import sujetsExamensRouter from "./sujetsExamens";
import epreuvesBlanChesRouter from "./epreuvesBlanches";
import planningRevisionsRouter from "./planningRevisions";
import bibliothequeRouter from "./bibliotheque";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(utilisateursRouter);
router.use(etablissementsRouter);
router.use(statsRouter);
router.use(elevesRouter);
router.use(anneesScolairesRouter);
router.use(filieresRouter);
router.use(creneauxRouter);
router.use(sallesRouter);
router.use(emploisDuTempsRouter);
router.use(classesRouter);
router.use(cahierTextesRouter);
router.use(appelsRouter);
router.use(notesRouter);
router.use(matieresConfigRouter);
router.use(bulletinsRouter);
router.use(conseilsClasseRouter);
router.use(absencesRouter);
router.use(notificationsRouter);
router.use(portailParentRouter);
router.use(messagesRouter);
router.use(rendezVousRouter);
router.use(annoncesRouter);
router.use(sujetsExamensRouter);
router.use(epreuvesBlanChesRouter);
router.use(planningRevisionsRouter);
router.use(bibliothequeRouter);

export default router;
